### ISSUE TITLE
Crash while replying and quickly switching to a different app

### ISSUE THREAD

**Issue by MKCOOL142** [LucasGGamerM/moshidon#138]
**Describe the bug**

i was replying to someone and then quickly changed to a different app from the app switcher, then moshidon crashed

**To reproduce**

unable to reliably reproduce it

**Version**

Moshidon version: 1.2.0+fork.99.moshinda

**Crash log**
[Device Brand]: OnePlus
[Device Model]: GM1913
[Display]: TQ1A.230205.002 test-keys
[Android Version]: 13
[Android API Level]: 33
[System Locale]: en_US
[Process ID]: 10661
[CPU ABI]: none
[Package Name]: org.joinmastodon.android.moshinda
[Version Name]: 1.2.0+fork.99.moshinda
[Version Code]: 99
[Error Type]: JVM
[Crash Time]: 2023-03-26T10:22:38.985
[Stack Trace]:
java.lang.IllegalStateException: ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)
	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7299)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6419)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6303)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6299)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2328)
	at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:571)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1589)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:676)
	at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:169)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4300)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4003)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4569)
	at android.view.View.layout(View.java:23700)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23700)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:671)
	at android.view.View.layout(View.java:23700)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23700)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:23700)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23700)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:23700)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23700)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:23700)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23700)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23700)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23700)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:23700)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:799)
	at android.view.View.layout(View.java:23700)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3999)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3372)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2328)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9088)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:832)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7926)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)

**Comment by LucasGGamerM** [comment]
I cannot reproduce this on the debug build. Can you see if you can try to reproduce it there?
