### ISSUE TITLE
logging into a pixelfed account crashes the app and then logging you out of all accounts

### ISSUE THREAD

**Issue by Mattis142** [LucasGGamerM/moshidon#158]
**To reproduce**

simply log into a pixelfed (in my case pixelfed.de) account and close the nightly or debug app, next time opening the app it'll crash and generate this log:

**Does this happen in the official app?**

no, it seems to be linked to the plemora integration which the official app doesn't have

[Device Brand]: OnePlus
[Device Model]: GM1913
[Display]: TQ1A.230205.002 test-keys
[Android Version]: 13
[Android API Level]: 33
[System Locale]: en_US
[Process ID]: 24754
[CPU ABI]: none
[Package Name]: org.joinmastodon.android.moshinda.debug
[Version Name]: 1.2.0+fork.99.moshinda-debug
[Version Code]: 99
[Error Type]: JVM
[Crash Time]: 2023-04-06T10:52:10.948
[Stack Trace]:
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.joinmastodon.android.moshinda.debug/org.joinmastodon.android.MainActivity}: java.lang.NullPointerException: Attempt to read from field 'org.joinmastodon.android.model.Instance$Pleroma org.joinmastodon.android.model.Instance.pleroma' on a null object reference in method 'void org.joinmastodon.android.fragments.HomeFragment.updateNotificationBadge()'
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3647)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3784)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2309)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7926)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
Caused by: java.lang.NullPointerException: Attempt to read from field 'org.joinmastodon.android.model.Instance$Pleroma org.joinmastodon.android.model.Instance.pleroma' on a null object reference in method 'void org.joinmastodon.android.fragments.HomeFragment.updateNotificationBadge()'
	at org.joinmastodon.android.fragments.HomeFragment.updateNotificationBadge(HomeFragment.java:340)
	at org.joinmastodon.android.fragments.HomeFragment.onCreateView(HomeFragment.java:139)
	at android.app.Fragment.performCreateView(Fragment.java:2505)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1303)
	at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1581)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1642)
	at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3052)
	at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3004)
	at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:185)
	at android.app.Activity.performCreate(Activity.java:8360)
	at android.app.Activity.performCreate(Activity.java:8331)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1425)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3628)
	... 12 more

**Comment by LucasGGamerM** [comment]
I cannot reproduce this, but I think I fixed this issue in 1f4970c0d20b606478ad826e9285f20ea51d3a26
