### ISSUE TITLE
Random crash while app launch

### ISSUE THREAD

**Issue by Mattis142** [LucasGGamerM/moshidon#165]
I launched the app and it crashed, the debug build is about ~2 days old at this point

I cannot replicate it and don't know what caused it

[Device Brand]: OnePlus
[Device Model]: GM1913
[Display]: TQ1A.230205.002 test-keys
[Android Version]: 13
[Android API Level]: 33
[System Locale]: en_US
[Process ID]: 31115
[CPU ABI]: none
[Package Name]: org.joinmastodon.android.moshinda.debug
[Version Name]: 1.2.0+fork.99.moshinda-debug
[Version Code]: 99
[Error Type]: JVM
[Crash Time]: 2023-04-13T00:29:45.138
[Stack Trace]:
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.joinmastodon.android.moshinda.debug/org.joinmastodon.android.MainActivity}: java.lang.ArrayIndexOutOfBoundsException: length=4; index=4
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3647)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3784)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2309)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7926)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=4; index=4
	at org.joinmastodon.android.fragments.HomeTabFragment.updateSwitcherIcon(HomeTabFragment.java:445)
	at org.joinmastodon.android.fragments.HomeTabFragment.navigateTo(HomeTabFragment.java:441)
	at org.joinmastodon.android.fragments.HomeTabFragment.onViewStateRestored(HomeTabFragment.java:628)
	at android.app.Fragment.restoreViewState(Fragment.java:576)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1326)
	at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1581)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1642)
	at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3052)
	at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3004)
	at android.app.Fragment.performActivityCreated(Fragment.java:2520)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1323)
	at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1581)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1642)
	at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3052)
	at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3004)
	at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:185)
	at android.app.Activity.performCreate(Activity.java:8360)
	at android.app.Activity.performCreate(Activity.java:8331)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1425)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3628)
	... 12 more

**Comment by LucasGGamerM** [comment]
It looks like an array out of bounds exception, which i have not come to see in my own usage. Its likely that its a one time thing with a broken configuration
