### ISSUE TITLE
Crash on following list 

### ISSUE THREAD

**Issue by Mattis142** [LucasGGamerM/moshidon#171]
**Describe the bug**

I looked through someone's following list using the new remote lookup, tapped a certain account (unfortunately do not know who anymore) and it caused my app to crash 
**To reproduce**

I haven't tried to reproduce it and will add a comment if I figure out a reliable way to reproduce it

**Crash log**

[Device Brand]: OnePlus
[Device Model]: GM1913
[Display]: TQ1A.230205.002 test-keys
[Android Version]: 13
[Android API Level]: 33
[System Locale]: en_US
[Process ID]: 17345
[CPU ABI]: none
[Package Name]: org.joinmastodon.android.moshinda.nightly
[Version Name]: 1.2.0+fork.99.moshinda-nightly+@2023-04-17
[Version Code]: 99
[Error Type]: JVM
[Crash Time]: 2023-04-18T00:22:56.097
[Stack Trace]:
java.lang.RuntimeException: java.lang.NullPointerException: Attempt to read from field 'java.lang.String org.joinmastodon.android.model.Account.id' on a null object reference in method 'void org.joinmastodon.android.fragments.v6.onCreate(android.os.Bundle)'
	at t.b.b(SourceFile:36)
	at v0.c$c.m0(SourceFile:32)
	at v0.c$c.d0(Unknown Source:0)
	at v0.d.accept(Unknown Source:4)
	at f1.z0$g.a(SourceFile:43)
	at f1.z0$g.onSuccess(Unknown Source:2)
	at me.grishka.appkit.api.a$a.run(SourceFile:12)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7926)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String org.joinmastodon.android.model.Account.id' on a null object reference in method 'void org.joinmastodon.android.fragments.v6.onCreate(android.os.Bundle)'
	at org.joinmastodon.android.fragments.v6.onCreate(SourceFile:54)
	at android.app.Fragment.performCreate(Fragment.java:2486)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1261)
	at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2431)
	at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2210)
	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2166)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2067)
	at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:822)
	at t.a.h(SourceFile:67)
	at t.b.b(SourceFile:29)
	... 14 more

**Comment by LucasGGamerM** [comment]
Its fixed now!
