### ISSUE TITLE
crash when tapping a certain post

### ISSUE THREAD

**Issue by Mattis142** [LucasGGamerM/moshidon#178]
**Describe the bug**

I looked at the mastodon.art external timeline that I have added and tapped this post:
https://mastodon.art/@marianarte/110232871653576973

it then crashed the debug build I was using (from 9pm) unfortunately the post doesn't appear to me when going to the profile of that user through the app either

**Crash log**

Generated by AppErrorsTracking
Project Url: https://github.com/KitsunePie/AppErrorsTracking

[Device Brand]: OnePlus
[Device Model]: GM1913
[Display]: TQ1A.230205.002 test-keys
[Android Version]: 13
[Android API Level]: 33
[System Locale]: en_US
[Process ID]: 13734
[CPU ABI]: none
[Package Name]: org.joinmastodon.android.moshinda.debug
[Version Name]: 1.2.0+fork.99.moshinda-debug
[Version Code]: 99
[Error Type]: JVM
[Crash Time]: 2023-04-20T22:15:48.673
[Stack Trace]:
java.lang.NullPointerException: Attempt to write to field 'boolean org.joinmastodon.android.model.Status.filterRevealed' on a null object reference in method 'void org.joinmastodon.android.fragments.StatusListFragment.lambda$onItemClick$0(org.joinmastodon.android.model.Status)'
	at org.joinmastodon.android.fragments.StatusListFragment.lambda$onItemClick$0(StatusListFragment.java:69)
	at org.joinmastodon.android.fragments.StatusListFragment.$r8$lambda$PDG53YpJT8pBTry3gYC2H7OqtE4(Unknown Source:0)
	at org.joinmastodon.android.fragments.StatusListFragment$$ExternalSyntheticLambda0.accept(Unknown Source:4)
	at org.joinmastodon.android.ui.utils.UiUtils$17.onSuccess(UiUtils.java:1127)
	at org.joinmastodon.android.ui.utils.UiUtils$17.onSuccess(UiUtils.java:1120)
	at me.grishka.appkit.api.APIRequest$1.run(APIRequest.java:29)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7926)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)

**Comment by LucasGGamerM** [comment]
Fixed on 13480ce
