### ISSUE TITLE
Moshidon crashes when attempting to compose in a auth-required server

### ISSUE THREAD

**Issue by CDN18** [LucasGGamerM/moshidon#209]
**Describe the bug**

I am trying to use a [Gotosocial](https://github.com/superseriousbusiness/gotosocial) instance through moshidon. Moshidon can log in normally, but it crashes when I click the compose button.

**To reproduce**

1. Set up a [Gotosocial](https://github.com/superseriousbusiness/gotosocial) instance, or a mastodon instance with `DISALLOW_UNAUTHENTICATED_API_ACCESS` enabled.
2. Login to the instance using moshidon
3. Click the compose ✏️ button in the bottom right corner

**Does this happen in the official app?**

No. The official app can't even log in to the instance.

Does this issue also occur with the respective upstream release?
No. I can compose a post successfully in Megalodon.

**Version**

Moshidon version: Nightly 2023-05-30

**Crash log**

Below are the crash stack trace of moshidon. I've also opened a issue in the gotosocial repo, see [superseriousbusiness/gotosocial#1862](https://github.com/superseriousbusiness/gotosocial/issues/1862)
```log
[Stack Trace]:
java.lang.RuntimeException: java.lang.UnsupportedOperationException
 at me.grishka.appkit.b.b(SourceFile:36)
 at org.joinmastodon.android.fragments.BaseStatusListFragment.onFabClick(SourceFile:19)
 at org.joinmastodon.android.fragments.HomeTabFragment.onFabClick(SourceFile:17)
 at org.joinmastodon.android.fragments.HomeTabFragment.u(Unknown Source:0)
 at org.joinmastodon.android.fragments.o4.onClick(Unknown Source:2)
 at android.view.View.performClick(View.java:7506)
 at android.view.View.performClickInternal(View.java:7483)
 at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
 at android.view.View$PerformClick.run(View.java:29357)
 at android.os.Handler.handleCallback(Handler.java:942)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7934)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
Caused by: java.lang.UnsupportedOperationException
 at java.util.AbstractList.add(AbstractList.java:153)
 at org.joinmastodon.android.ui.CustomEmojiPopupKeyboard.onCreateView(SourceFile:188)
 at org.joinmastodon.android.ui.PopupKeyboard.ensureView(SourceFile:5)
 at org.joinmastodon.android.ui.PopupKeyboard.getView(SourceFile:1)
 at org.joinmastodon.android.fragments.ComposeFragment.onCreateContentView(SourceFile:68)
 at me.grishka.appkit.fragments.f.onCreateView(SourceFile:18)
 at android.app.Fragment.performCreateView(Fragment.java:2505)
 at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1303)
 at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2431)
 at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2210)
 at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2166)
 at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2067)
 at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:822)
 at me.grishka.appkit.a.showFragment(SourceFile:67)
 at me.grishka.appkit.b.b(SourceFile:29)
 ... 16 more
```

**Comment by LucasGGamerM** [comment]
Do you mind trying with the latest nightly release? You can download it here https://nightly.link/LucasGGamerM/moshidon/workflows/nightly-builds/master/moshidon-nightly.apk.zip 

This build does not conflict with the official build. Please try it on this release!

**Comment by CDN18** [comment]
Hi, I've re-done the test release, moshidon crashes with the same error.

Additional info:
OS: Android 13 arm64

**Comment by CDN18** [comment]
Update: I have been using the nightly version before. After clearing the previous data and logging in again, I can compose posts without any problem. Thank you for your work and assistance!

**Comment by LucasGGamerM** [comment]
Lovely!

> Update: I have been using the nightly version before. After clearing the previous data and logging in again, I can compose posts without any problem. Thank you for your work and assistance!

Lovely! I am happy it could be cleared up!
