### ISSUE TITLE
[Friendica] Crash when opening notifications

### ISSUE THREAD

**Issue by eengnr** [LucasGGamerM/moshidon#212]
**Describe the bug**
Hi, I'm using your app with a Friendica account! It crashes if I try to open the notifications overview in the app.
I don't know if the app should be compatible with Friendica, but maybe you can have a look 😊

**To reproduce**
1. Open the app
2. Tap the "bell" icon

**Does this happen in the official app?**
It does not happen with Megalodon Version 1.2.3+fork.91

**Version**
Moshidon version: Version 1.3.0+fork.100.moshinda

**Crash log**
```
FATAL EXCEPTION: main
Process: org.joinmastodon.android.moshinda, PID: 7525
java.lang.NullPointerException: Attempt to read from field 'org.joinmastodon.android.model.Marker org.joinmastodon.android.model.Markers.notifications' on a null object reference in method 'void org.joinmastodon.android.fragments.NotificationsListFragment$1.onSuccess(org.joinmastodon.android.model.CacheablePaginatedResponse)'
	at org.joinmastodon.android.fragments.NotificationsListFragment$1.onSuccess(SourceFile:12)
	at org.joinmastodon.android.fragments.NotificationsListFragment$1.onSuccess(SourceFile:1)
	at org.joinmastodon.android.api.CacheController$2.onSuccess(SourceFile:4)
	at org.joinmastodon.android.api.CacheController$2.onSuccess(SourceFile:1)
	at me.grishka.appkit.api.a$a.run(SourceFile:12)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7884)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by LucasGGamerM** [comment]
Btw, you *can* install the nightly version alongside the stable version and use either interchangeably
