### ISSUE TITLE
Crashing due to UnifiedPush notifications

### ISSUE THREAD

**Issue by benjja** [LucasGGamerM/moshidon#289]
**Describe the bug**

If UnifiedPush is enabled, the app crashes every time a notification should be shown. This behavior is independent of the used UnifiedPush backend.

**To reproduce**

Enable UnifiedPush notifications.

**Does this happen in the official app?**

Does this issue also occur with the respective upstream release?
> No

**Screenshots and screen recordings**

![Imagepipe_2](https://github.com/LucasGGamerM/moshidon/assets/1878125/b237a687-c78d-4008-9353-34f8bdcf42bf)

**Version**

Moshidon version: Version 2.1.4+fork.102.moshinda-nightly+@2023-10-26

**Crash log**

```
type: crash
osVersion: google/sunfish/sunfish:13/TQ3A.230805.001/2023100300:user/release-keys
package: org.joinmastodon.android.moshinda.nightly:102
process: org.joinmastodon.android.moshinda.nightly
processUptime: 4009 + 1163 ms
installer: com.android.packageinstaller

java.lang.IllegalStateException: Unexpected value: STATUS
	at org.joinmastodon.android.model.PushNotification.fromNotification(PushNotification.java:51)
	at org.joinmastodon.android.PushNotificationReceiver.notifyUnifiedPush(PushNotificationReceiver.java:159)
	at org.joinmastodon.android.UnifiedPushNotificationReceiver$1.lambda$onSuccess$0(UnifiedPushNotificationReceiver.java:75)
	at org.joinmastodon.android.UnifiedPushNotificationReceiver$1$$ExternalSyntheticLambda0.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at me.grishka.appkit.utils.WorkerThread.run(WorkerThread.java:54)

```

**Comment by Sythelux** [comment]
I don't want to make a new Ticket, because the Issue is basically the same, but the error is different. My Moshidon crashes on Startup after I set Unified Push and it is related to unifiedpush

logcat at that time:
```logcat
07-01 19:24:31.728 15721 15721 E AndroidRuntime: FATAL EXCEPTION: main
07-01 19:24:31.728 15721 15721 E AndroidRuntime: Process: org.joinmastodon.android.moshinda, PID: 15721
07-01 19:24:31.728 15721 15721 E AndroidRuntime: java.lang.RuntimeException: Unable to create application org.joinmastodon.android.MastodonApp: org.unifiedpush.android.connector.UnifiedPush$VapidNotValidException
07-01 19:24:31.728 15721 15721 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6874)
07-01 19:24:31.728 15721 15721 E AndroidRuntime: 	at android.app.ActivityThread.access$1500(ActivityThread.java:255)
07-01 19:24:31.728 15721 15721 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2061)
07-01 19:24:31.728 15721 15721 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-01 19:24:31.728 15721 15721 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
07-01 19:24:31.728 15721 15721 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
07-01 19:24:31.728 15721 15721 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8005)
07-01 19:24:31.728 15721 15721 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-01 19:24:31.728 15721 15721 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
07-01 19:24:31.728 15721 15721 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1039)
07-01 19:24:31.728 15721 15721 E AndroidRuntime: Caused by: org.unifiedpush.android.connector.UnifiedPush$VapidNotValidException
07-01 19:24:31.728 15721 15721 E AndroidRuntime: 	at org.unifiedpush.android.connector.UnifiedPush.register(UnifiedPush.kt:252)
07-01 19:24:31.728 15721 15721 E AndroidRuntime: 	at org.unifiedpush.android.connector.UnifiedPush.register(UnifiedPush.kt:228)
07-01 19:24:31.728 15721 15721 E AndroidRuntime: 	at org.unifiedpush.android.connector.UnifiedPush.register(UnifiedPush.kt:200)
07-01 19:24:31.728 15721 15721 E AndroidRuntime: 	at org.joinmastodon.android.utils.UnifiedPushHelper.registerAllAccounts(UnifiedPushHelper.java:49)
07-01 19:24:31.728 15721 15721 E AndroidRuntime: 	at org.joinmastodon.android.MastodonApp.onCreate(MastodonApp.java:32)
07-01 19:24:31.728 15721 15721 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1212)
07-01 19:24:31.728 15721 15721 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6869)
07-01 19:24:31.728 15721 15721 E AndroidRuntime: 	... 9 more
```
