### ISSUE TITLE
Janky animations in tab buttons

### ISSUE THREAD

**Issue by jcrabapple** [LucasGGamerM/moshidon#334]
**Describe the bug**

Animations when tapping on the tab buttons at the bottom are delayed and slow.

**To reproduce**

1. Tap on the Home button
2. Watch the animation have a very low FPS 

**Does this happen in the official app?**

Does this issue also occur with the respective upstream release?
> No

**Screenshots and screen recordings**

https://albums.ente.io?t=fzb7vU3L#3qePP4GcuqKDz5XXcnvmDB5xMwqSsVrqY5GKvebPv33r

**Version**

Moshidon version: [e.g. v1.1.4+fork.#]

**Crash log**

If you know your way around Android development tools, please consider attaching a crash log, if possible.

2.1.4+fork.103.moshinda (103)
2024-01-21T14:42:04.977Z

java.lang.IllegalStateException: Unexpected value: STATUS
	at org.joinmastodon.android.model.PushNotification.fromNotification(PushNotification.java:51)
	at org.joinmastodon.android.PushNotificationReceiver.notifyUnifiedPush(PushNotificationReceiver.java:159)
	at org.joinmastodon.android.UnifiedPushNotificationReceiver$1.lambda$onSuccess$0(UnifiedPushNotificationReceiver.java:75)
	at org.joinmastodon.android.UnifiedPushNotificationReceiver$1.$r8$lambda$4J7AuBytjmt8335OwYDlx1gnhvU(UnifiedPushNotificationReceiver.java:0)
	at org.joinmastodon.android.UnifiedPushNotificationReceiver$1$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at me.grishka.appkit.utils.WorkerThread.run(WorkerThread.java:54)

**Comment by LucasGGamerM** [comment]
That is very much an annoying and known bug, which I don't know how it came to be

**Comment by jcrabapple** [comment]
It happens on Megalodon too.

**Comment by DerpyPlayz18** [comment]
The ripple effect isn't the only thing affected, it's also the loading spinner that appears when tapping buttons such as _load newer posts_. I also noticed the animations get stuttery only when the interface is still (for example when you are not scrolling or interacting). Maybe some optimization (something like variable refresh rate) "optimizes" the animation

**Comment by LucasGGamerM** [comment]
Hopefully after the merge this gets just working again
