### ISSUE TITLE
App crash on hashtag autocomplete

### ISSUE THREAD

**Issue by doctorambient** [LucasGGamerM/moshidon#434]
**Describe the bug**

When typing a hashtag, selecting one of the autocomplete suggestions causes the app to fully crash. On restart, the post that was being edited is lost.

**To reproduce**

This is an intermittent bug. It does not happen on every occasion of selecting a hashtag auto-completion.

1. Start typing a hashtag
2. When you see a suggestion that you want, select it.
3. Once in a long while the app crashes. 

Based on my usage pattern, this is likely an event that happens on the order of 1 out of 200 times.

**Does this happen in the official app?**

I do not use the official app, so I do not know if it has this problem. It does not happen to me on the desktop access to mastodon.social, nor has it happened to me on the use of the web interface from my phone. (Although I cannot recall if that does autocomplete, anyway.)

Does this issue also occur with the respective upstream release?
> Yes

As this is forked from Megalodon the answer is yes. It happens there much more often. It is a known bug there as well.

> In case it does, please consider filing an [upstream bug report](https://github.com/mastodon/mastodon-android/issues) instead.
> If this bug is seriously impacting your usage or you think I might want to try to fix it for Moshidon, feel free to still create this issue!

**Screenshots and screen recordings**

None. See crashlog below.

**Version**

2.3.0+fork.105.moshinda-play (105)

**Crash log**

```text
2.3.0+fork.105.moshinda-play (105)
2024-06-22T16:34:19.221Z

java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionHashtagViewHolder{f9befce position=4 id=-1, oldPos=-1, pLpos:-1 no parent} me.grishka.appkit.views.UsableRecyclerView{e196a8f VFED..... ........ 0,0-1080,168}, adapter:org.joinmastodon.android.ui.viewcontrollers.ComposeAutocompleteViewController$HashtagsAdapter@9864b32, layout:androidx.recyclerview.widget.LinearLayoutManager@3c37083, context:org.joinmastodon.android.MainActivity@168f8e7
	at androidx.recyclerview.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:6159)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6342)
	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:287)
	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:344)
	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:360)
	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:367)
	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:398)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Comment by LucasGGamerM** [comment]
Fixed with 0de346c
