### ISSUE TITLE
App crash on hashtag lookup

### ISSUE THREAD

**Issue by TheCodeJanitor-dotcom** [LucasGGamerM/moshidon#517]
**Describe the bug**

When typing multiple hashtags, the population of suggestions causes the app to fully crash. 
*This occurs even if none of the suggested hashtags are selected*. 
On restart, the post being created/edited is lost.

NOTE: This behavior is *different* from issue #434 

**To reproduce**

1. Type a common hashtag.
2. Allow the suggested hashtag list to populate, but *do not* select a suggestion.
3. Enter a space, then type *another* hashtag.
4. Repeat from step 2.
5. Typically, the app will crash during entry of the second or third hashtag.

**Does this happen in the official app?**

> Yes

Does this issue also occur with the respective upstream release?

> Unknown / untried

**Version**

Moshidon version: v2.3.0+fork.107.moshinda-play (107)

**Crash log**

```
2.3.0+fork.107.moshinda-play (107)
2024-08-22T16:39:47.656Z

java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 4(offset:4).state:21 me.grishka.appkit.views.UsableRecyclerView{b33b485 VFED..... ........ 0,0-1080,161 aid=1073752116}, adapter:org.joinmastodon.android.ui.viewcontrollers.ComposeAutocompleteViewController$HashtagsAdapter@33cf939, layout:androidx.recyclerview.widget.LinearLayoutManager@ffbab7e, context:org.joinmastodon.android.MainActivity@f72dd78
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6367)
	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:287)
	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:344)
	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:360)
	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:367)
	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:398)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

```

**Comment by LucasGGamerM** [comment]
Fixed with 0de346c
