### ISSUE TITLE
Possible Memory Leak?

### ISSUE THREAD

**Issue by deivpaukst** [LucasGGamerM/moshidon#530]
**Describe the bug**

The app seems to slowly start lagging after some time of use (scrolling timeline, reading posts, doing anything really) and then finally crash after becoming unusable. This problem has existed even back when I used Megalodon.

**To reproduce**

1. Browse the fediverse.
2. App slowly starts freezing once every so often.
3. Eventually it freezes for a longer time and then finally crashes.

**Does this happen in the official app?**

Does this issue also occur with the respective upstream release?
> I haven't tested it

> In case it does, please consider filing an [upstream bug report](https://github.com/mastodon/mastodon-android/issues) instead.
> If this bug is seriously impacting your usage or you think I might want to try to fix it for Moshidon, feel free to still create this issue!

**Screenshots and screen recordings**

If applicable, add screenshots (and screen recordings, if possible) to help explain your problem.

**Version**

Moshidon version:
2.3.0+fork.107.moshinda-nightly+@2024-09-02 (107)
2024-09-03T10:02:48.382Z

**Crash log**

```
2.3.0+fork.107.moshinda-nightly+@2024-09-02 (107)
2024-09-03T10:02:48.382Z

java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 687192 free bytes and 671KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:212)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:172)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
```

If you know your way around Android development tools, please consider attaching a crash log, if possible.

**Comment by LucasGGamerM** [comment]
I hate this bug. I might try to reduce the emulator's ram to see if I can catch anything. Thank you for reporting!

**Comment by KaiserCalm** [comment]
If it helps, I'm using DivestOS 20 (Android 13) with Secure App Spawning enabled.
![Screenshot_20240903-213100_Settings](https://github.com/user-attachments/assets/4f2197bb-d97e-421c-a994-016fdab65291)

**Comment by deivpaukst** [comment]
@LucasGGamerM Heyo, it's been a bit, I'm now on GrapheneOS and I'm still experiencing this issue. I'm gonna share both the log from the app and what GrapheneOS is giving me.

App log:
```
2.3.0+fork.110.moshinda-github (110)
2025-06-16T09:54:17.175Z

java.lang.OutOfMemoryError: Failed to allocate a 112 byte allocation with 2597776 free bytes and 2536KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at java.lang.StringFactory.newStringFromBytes(Native Method)
	at java.lang.StringLatin1.newString(StringLatin1.java:770)
	at java.lang.StringBuilder.toString(StringBuilder.java:474)
	at me.grishka.appkit.imageloader.requests.UrlImageLoaderRequest.<init>(UrlImageLoaderRequest.java:27)
	at me.grishka.appkit.imageloader.requests.UrlImageLoaderRequest.<init>(UrlImageLoaderRequest.java:36)
	at me.grishka.appkit.imageloader.requests.UrlImageLoaderRequest.<init>(UrlImageLoaderRequest.java:44)
	at org.joinmastodon.android.ui.CustomEmojiPopupKeyboard$SingleCategoryAdapter.lambda$new$0(CustomEmojiPopupKeyboard.java:242)
	at org.joinmastodon.android.ui.CustomEmojiPopupKeyboard$SingleCategoryAdapter.$r8$lambda$MVSWsH80noB7_zYH7nOGF_m6r4Q(CustomEmojiPopupKeyboard.java:0)
	at org.joinmastodon.android.ui.CustomEmojiPopupKeyboard$SingleCategoryAdapter$$ExternalSyntheticLambda0.apply(R8$$SyntheticClass:0)
	at j$.util.stream.o.accept(SourceFile:195)
	at j$.util.a.forEachRemaining(SourceFile:720)
	at j$.util.stream.a.t(SourceFile:484)
	at j$.util.stream.a.K(SourceFile:474)
	at j$.util.stream.x1.b(SourceFile:913)
	at j$.util.stream.a.w(SourceFile:234)
	at j$.util.stream.f2.collect(SourceFile:578)
	at org.joinmastodon.android.ui.CustomEmojiPopupKeyboard$SingleCategoryAdapter.<init>(CustomEmojiPopupKeyboard.java:242)
	at org.joinmastodon.android.ui.CustomEmojiPopupKeyboard.onCreateView(CustomEmojiPopupKeyboard.java:119)
	at org.joinmastodon.android.ui.PopupKeyboard.ensureView(PopupKeyboard.java:41)
	at org.joinmastodon.android.ui.PopupKeyboard.getView(PopupKeyboard.java:47)
	at org.joinmastodon.android.ui.displayitems.EmojiReactionsStatusDisplayItem$Holder.onBind(EmojiReactionsStatusDisplayItem.java:207)
	at org.joinmastodon.android.ui.displayitems.EmojiReactionsStatusDisplayItem$Holder.onBind(EmojiReactionsStatusDisplayItem.java:159)
	at me.grishka.appkit.utils.BindableViewHolder.bind(BindableViewHolder.java:33)
	at org.joinmastodon.android.fragments.BaseStatusListFragment$DisplayItemsAdapter.onBindViewHolder(BaseStatusListFragment.java:1226)
	at org.joinmastodon.android.fragments.BaseStatusListFragment$DisplayItemsAdapter.onBindViewHolder(BaseStatusListFragment.java:1210)
	at me.grishka.appkit.views.UsableRecyclerView$FooterRecyclerAdapter.onBindViewHolder(UsableRecyclerView.java:433)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7256)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7339)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6197)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6463)
	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:287)
	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:344)
	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:360)
	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:367)
	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:398)
	at android.os.Handler.handleCallback(Handler.java:991)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8973)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)

```

GrapheneOS log is attached here:
[Moshidon log 51580c1970c0.txt](https://github.com/user-attachments/files/20754538/Moshidon.log.51580c1970c0.txt)
