### ISSUE TITLE
Constantly getting "Too many requests" on Mastodon.social

### ISSUE THREAD

**Issue by Cragsand** [LucasGGamerM/moshidon#536]
**Describe the bug**

Regular use on Mastodon.social gets too easily rate limited. They probably reduced how many requests you can do due to the influx of users from Brazil after they banned Xshitter but refreshing the home feed once directly after opening the app, shouldn't get rate limited.

Waiting 2 minutes fixes the rate limit but seeing it at least once everytime i open the app after leaving it for hours.

**To reproduce**

1. Go to home feed
2. Update home feed
4. See error "too many requests"

**Does this happen in the official app?**

Does not happen in the official app.

Does this issue also occur with the respective upstream release?

Not sure what this means but I'm using 2.3.0+fork.107.moshinda (107)
Latest update on fdroid

> In case it does, please consider filing an [upstream bug report](https://github.com/mastodon/mastodon-android/issues) instead.
> If this bug is seriously impacting your usage or you think I might want to try to fix it for Moshidon, feel free to still create this issue!

**Screenshots and screen recordings**

If applicable, add screenshots (and screen recordings, if possible) to help explain your problem.

**Version**

2.3.0+fork.107.moshinda (107)

**Crash log**

No crash

**Comment by diogotcorreia** [comment]
Chiming in to say that I get the same problem with https://masto.pt

Just normal usage and somewhat frequent (few times a week)

**Comment by dpreuss321** [comment]
Me too. Intermittent, hasn't happened in over a week, not I cannot post. Was just posting a simple, short post, only one hashtag #mastodon, no images, no @ . 

Tried twice in quick succession, both same error: Too many requests. Tried again after 9 min pause: works.

Log attached.

2.3.0+fork.107.moshinda-nightly+@2024-09-09 (107)
2024-11-07T08:44:56.421Z

java.lang.RuntimeException: Could not dispatch event: class org.joinmastodon.android.events.PollUpdatedEvent to handler [EventHandler public void org.joinmastodon.android.fragments.StatusListFragment$EventListener.onPollUpdated(org.joinmastodon.android.events.PollUpdatedEvent)]: toIndex = 127
	at com.squareup.otto.Bus.throwRuntimeException(Bus.java:460)
	at com.squareup.otto.Bus.dispatch(Bus.java:387)
	at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:368)
	at com.squareup.otto.Bus.post(Bus.java:337)
	at com.squareup.otto.AsyncBus.post(AsyncBus.java:56)
	at org.joinmastodon.android.E.post(E.java:12)
	at org.joinmastodon.android.fragments.BaseStatusListFragment$5.onSuccess(BaseStatusListFragment.java:694)
	at org.joinmastodon.android.fragments.BaseStatusListFragment$5.onSuccess(BaseStatusListFragment.java:691)
	at me.grishka.appkit.api.APIRequest$1.run(APIRequest.java:29)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: java.lang.IndexOutOfBoundsException: toIndex = 127
	at java.util.AbstractList.subListRangeCheck(AbstractList.java:509)
	at java.util.ArrayList.subList(ArrayList.java:1207)
	at org.joinmastodon.android.fragments.BaseStatusListFragment.updatePoll(BaseStatusListFragment.java:602)
	at org.joinmastodon.android.fragments.StatusListFragment$EventListener.onPollUpdated(StatusListFragment.java:395)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.squareup.otto.EventHandler.handleEvent(EventHandler.java:89)
	at com.squareup.otto.Bus.dispatch(Bus.java:385)
	... 15 more

**Comment by TomCasavant** [comment]
I'm getting the same issue for my personal server, it's not nonstop but it'll come up every few days and the app will be unusable for an hour or so

**Comment by Skylark13** [comment]
Same for me on mastodon.gamedev.place

**Comment by vorboyvo** [comment]
Same for me on the server my account is hosted on, though some others using moshidon are apparently not getting this problem on the same server

**Comment by pstorch** [comment]
Same for fulda.social instance

**Comment by IAmYhvr** [comment]
This has happened a couple times per day for me generally, but today it has happened several dozen times and it's making the app nearly unusable. If there's any debugging steps I can take or logs I can provide that might be helpful, please let me know ^^ (wetdry.world)

Other mastodon clients seem unaffected by the purported ratelimit while it's happening. It's just Moshidon

**Comment by dpreuss321** [comment]
I am still experiencing this, only on some days, but then consistently over
a period of hours.
Clearing cache, restarting app, these do not seem to help.
And then it suddenly reverts to normal.

I look forward to news that this has been solved ...

**Comment by TomCasavant** [comment]
> I'm getting the same issue for my personal server, it's not nonstop but it'll come up every few days and the app will be unusable for an hour or so 

Recently, I moved my server (and all my clients) to a place with significantly better internet up/down, and I have not experienced this issue since. I wonder if there's a request that retries after it times out and repeatedly does that until it can't make requests anymore?

**Comment by sloanlance** [comment]
Although this issue was opened about _**a YEAR AND A HALF ago**_, it has not been resolved and is still a major problem.  It makes Moshidon completely unusable for me at unpredictable times. Each time it happens, if I use the official Mastodon client for Android instead, it doesn't have a problem. If I then immediately switch back to Moshidon, the problem persists.

**Comment by Kreavita** [comment]
same issue.

**Comment by t9mike** [comment]
Chiming in: this is nuts. All I was trying to do was search for a user and @ them in a message. Jeez.
