### ISSUE TITLE
Crash on opening draft

### ISSUE THREAD

**Issue by pietsch** [LucasGGamerM/moshidon#537]
**Describe the bug**

I have one stored draft post. When I try to resume editing it, I see the draft for a split second, and then the app crashes.

**To reproduce**

1. Go to my profile
2. Tap on folder symbol near the upper right corner

**Does this happen in the official app?**

Does this issue also occur with the respective upstream release?
> I don't know. I never used the official app or Megalodon.

**Version**

Moshidon version: v2.3.0+fork.#107 from F-Droid

**Crash log**

```
type: crash
osVersion: google/shiba/shiba:14/AP2A.240905.003/2024090400:user/release-keys
package: org.joinmastodon.android.moshinda:107
process: org.joinmastodon.android.moshinda
processUptime: 4280 + 231 ms
installer: com.android.packageinstaller

java.lang.ClassCastException: org.joinmastodon.android.model.Status cannot be cast to org.joinmastodon.android.model.ScheduledStatus
	at org.joinmastodon.android.fragments.ScheduledStatusListFragment.buildDisplayItems(ScheduledStatusListFragment.java:35)
	at org.joinmastodon.android.fragments.BaseStatusListFragment.updateStatusWithQuote(BaseStatusListFragment.java:728)
	at org.joinmastodon.android.ui.displayitems.StatusDisplayItem$1.onSuccess(StatusDisplayItem.java:437)
	at org.joinmastodon.android.ui.displayitems.StatusDisplayItem$1.onSuccess(StatusDisplayItem.java:432)
	at me.grishka.appkit.api.APIRequest$1.run(APIRequest.java:29)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
```

**Comment by FineFindus** [comment]
Already fixed with https://github.com/LucasGGamerM/moshidon/pull/505
