### ISSUE TITLE
Switching between display mode crashes app

### ISSUE THREAD

**Issue by MKCOOL142** [LucasGGamerM/moshidon#66]
Rapidly going from light to dark mode or quickly enabling and disabling the true black mode causes the app to crash, additionally a toast notification appears about "no update being available" which doesn't make sense as I haven't tapped the option to check for updates 
**To Reproduce**
1. Go to Settings
2. Quickly change between light and dark mode back and forth 

I also have this crash log: 
```
type: crash
osVersion: OnePlus/OnePlus7Pro/OnePlus7Pro:13/TKQ1.221114.001/eng.npv12.20221211.185304:user/release-keys
package: org.joinmastodon.android.moshinda:88
process: org.joinmastodon.android.moshinda

java.lang.RuntimeException: Unable to pause activity {org.joinmastodon.android.moshinda/org.joinmastodon.android.MainActivity}: java.lang.ArrayIndexOutOfBoundsException: length=244; index=-1
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5096)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5047)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5769)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5690)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:71)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:61)
	at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:5758)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2320)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7951)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=244; index=-1
	at java.util.ArrayList.get(ArrayList.java:439)
	at org.joinmastodon.android.fragments.HomeTimelineFragment.onHidden(HomeTimelineFragment.java:101)
	at me.grishka.appkit.fragments.AppKitFragment.onPause(AppKitFragment.java:513)
	at org.joinmastodon.android.fragments.BaseStatusListFragment.onPause(BaseStatusListFragment.java:656)
	at android.app.Fragment.performPause(Fragment.java:2706)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1358)
	at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1581)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1642)
	at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3052)
	at android.app.FragmentManagerImpl.dispatchPause(FragmentManager.java:3018)
	at android.app.Fragment.performPause(Fragment.java:2702)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1358)
	at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1581)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1642)
	at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3052)
	at android.app.FragmentManagerImpl.dispatchPause(FragmentManager.java:3018)
	at android.app.Fragment.performPause(Fragment.java:2702)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1358)
	at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1581)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1642)
	at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3052)
	at android.app.FragmentManagerImpl.dispatchPause(FragmentManager.java:3018)
	at android.app.FragmentController.dispatchPause(FragmentController.java:218)
	at android.app.Activity.performPause(Activity.java:8515)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1594)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5086)
	... 17 more

```

**Comment by LucasGGamerM** [comment]
I fixed it sometime earlier today. Thank you for reporting it though!
