### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by pandalec** [LucasGGamerM/moshidon#93]
Hey! 

I get the following error on start. I tried to delete cache first, then storage and relogged onto the instance. After log in, I get the same error. Haven't done any special yesterday. Boosted stuff and saved a toot for later use.

```
type: crash
osVersion: google/cheetah/cheetah:13/TQ1A.230205.002/2023021000:user/release-keys
package: org.joinmastodon.android.moshinda:94
process: org.joinmastodon.android.moshinda
processUptime: 204 + 293 ms

java.lang.RuntimeException: Unable to start activity ComponentInfo{org.joinmastodon.android.moshinda/org.joinmastodon.android.MainActivity}: java.lang.StringIndexOutOfBoundsException: length=0; index=0
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3646)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3783)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7879)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.StringIndexOutOfBoundsException: length=0; index=0
	at java.lang.String.charAt(Native Method)
	at android.graphics.Color.parseColor(Color.java:1383)
	at org.joinmastodon.android.fragments.ProfileFragment.bindHeaderView(ProfileFragment.java:580)
	at org.joinmastodon.android.fragments.ProfileFragment.onCreateContentView(ProfileFragment.java:372)
	at me.grishka.appkit.fragments.LoaderFragment.onCreateView(LoaderFragment.java:78)
	at android.app.Fragment.performCreateView(Fragment.java:2505)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1303)
	at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2431)
	at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2210)
	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2166)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2067)
	at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3057)
	at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3004)
	at android.app.Fragment.performActivityCreated(Fragment.java:2520)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1323)
	at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1581)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1642)
	at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3052)
	at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3004)
	at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:185)
	at android.app.Activity.performCreate(Activity.java:8360)
	at android.app.Activity.performCreate(Activity.java:8331)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1422)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3627)
	... 14 more
```

**Comment by TazzerMAN** [comment]
Same here 🥺

**Comment by LucasGGamerM** [comment]
That is a crash that happens when the app is trying to parse colors that don't exist. By any chance, are you using a glitch SOC instance?

**Comment by LucasGGamerM** [comment]
Yeah, I already merged that. I will announce a new release once I get the custom local timelines thing ready
